from datetime import datetime
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from .database import Base

class SimulationRun(Base):
    __tablename__="simulation_runs"
    id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(120)); seed: Mapped[int]=mapped_column(Integer); current_month: Mapped[int]=mapped_column(Integer,default=0); status: Mapped[str]=mapped_column(String(30),default="ACTIVE"); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
class Agent(Base):
    __tablename__="agents"
    id: Mapped[int]=mapped_column(primary_key=True); agent_code: Mapped[str]=mapped_column(String(30),unique=True,index=True); name: Mapped[str]=mapped_column(String(100)); age: Mapped[int]=mapped_column(Integer); area_type: Mapped[str]=mapped_column(String(20)); occupation: Mapped[str]=mapped_column(String(60)); industry: Mapped[str]=mapped_column(String(60)); skill_level: Mapped[str]=mapped_column(String(15),index=True); employment_status: Mapped[str]=mapped_column(String(20),index=True); family_size: Mapped[int]=mapped_column(Integer); base_monthly_income: Mapped[float]=mapped_column(Float); base_food_expense: Mapped[float]=mapped_column(Float); base_housing_expense: Mapped[float]=mapped_column(Float); base_transport_expense: Mapped[float]=mapped_column(Float); base_other_expense: Mapped[float]=mapped_column(Float); initial_savings: Mapped[float]=mapped_column(Float); initial_debt: Mapped[float]=mapped_column(Float); goal: Mapped[str]=mapped_column(String(60)); goal_amount: Mapped[float]=mapped_column(Float); home_x: Mapped[int]=mapped_column(Integer); home_y: Mapped[int]=mapped_column(Integer); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Job(Base):
    __tablename__="jobs"; id: Mapped[int]=mapped_column(primary_key=True); title: Mapped[str]=mapped_column(String(100)); industry: Mapped[str]=mapped_column(String(60)); required_skill: Mapped[str]=mapped_column(String(15)); monthly_salary: Mapped[float]=mapped_column(Float); capacity: Mapped[int]=mapped_column(Integer); filled_positions: Mapped[int]=mapped_column(Integer,default=0); location_x: Mapped[int]=mapped_column(Integer); location_y: Mapped[int]=mapped_column(Integer); active: Mapped[bool]=mapped_column(Boolean,default=True)
class Product(Base):
    __tablename__="products"; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(80)); category: Mapped[str]=mapped_column(String(30)); base_price: Mapped[float]=mapped_column(Float); current_price: Mapped[float]=mapped_column(Float); essential: Mapped[bool]=mapped_column(Boolean); unit: Mapped[str]=mapped_column(String(20))
class Location(Base):
    __tablename__="locations"; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(80)); location_type: Mapped[str]=mapped_column(String(30)); x: Mapped[int]=mapped_column(Integer); y: Mapped[int]=mapped_column(Integer); capacity: Mapped[int]=mapped_column(Integer)
class EconomicEvent(Base):
    __tablename__="economic_events"; id: Mapped[int]=mapped_column(primary_key=True); simulation_run_id: Mapped[int]=mapped_column(ForeignKey("simulation_runs.id"),index=True); event_type: Mapped[str]=mapped_column(String(40)); magnitude: Mapped[float]=mapped_column(Float); start_month: Mapped[int]=mapped_column(Integer); duration_months: Mapped[int]=mapped_column(Integer); target: Mapped[str]=mapped_column(String(60),default="ALL"); description: Mapped[str]=mapped_column(String(300)); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AgentHistory(Base):
    __tablename__="agent_history"; id: Mapped[int]=mapped_column(primary_key=True); simulation_run_id: Mapped[int]=mapped_column(ForeignKey("simulation_runs.id")); agent_id: Mapped[int]=mapped_column(ForeignKey("agents.id")); month: Mapped[int]=mapped_column(Integer); gross_income: Mapped[float]=mapped_column(Float); net_income: Mapped[float]=mapped_column(Float); food_expense: Mapped[float]=mapped_column(Float); housing_expense: Mapped[float]=mapped_column(Float); transport_expense: Mapped[float]=mapped_column(Float); other_expense: Mapped[float]=mapped_column(Float); total_expense: Mapped[float]=mapped_column(Float); savings: Mapped[float]=mapped_column(Float); debt: Mapped[float]=mapped_column(Float); employment_status: Mapped[str]=mapped_column(String(20)); job_id: Mapped[int|None]=mapped_column(ForeignKey("jobs.id"),nullable=True); risk_probability: Mapped[float]=mapped_column(Float); risk_class: Mapped[str]=mapped_column(String(20)); decision: Mapped[str]=mapped_column(String(40)); current_x: Mapped[int]=mapped_column(Integer); current_y: Mapped[int]=mapped_column(Integer); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
Index("ix_history_run_month", AgentHistory.simulation_run_id, AgentHistory.month); Index("ix_history_agent_month", AgentHistory.agent_id, AgentHistory.month)
